import { AppPermission, AppRole } from './types';

export const ROLE_DEFAULT_PERMISSIONS: Record<AppRole, AppPermission[]> = {
  Admin: [
    'users.manage',
    'roles.assign',
    'permissions.manage',
    'business.view',
    'business.edit',
    'sales.view',
    'sales.create',
    'sales.reverse',
    'quotations.view',
    'quotations.create',
    'quotations.convert',
    'invoices.view',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'inventory.adjust',
    'inventory.restock',
    'customers.view',
    'customers.create',
    'customers.edit',
    'customers.ledger.view',
    'accounting.access',
    'expenses.view',
    'expenses.create',
    'expenses.edit',
    'reports.financial.view',
    'reports.dashboard.view',
    'reports.sales.view',
    'reports.inventory.view',
  ],
  SalesManager: [
    'business.view',
    'sales.view',
    'sales.create',
    'quotations.view',
    'quotations.create',
    'quotations.convert',
    'invoices.view',
    'customers.view',
    'customers.create',
    'customers.edit',
    'customers.ledger.view',
    'inventory.view',
    'reports.dashboard.view',
    'reports.sales.view',
    'reports.inventory.view',
  ],
  Accountant: [],
};
