'use client';

import { ArrowLeft, FileText, Printer, ShieldAlert } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';
import { useState } from 'react';

import { useBusiness } from '../../src/context/BusinessContext';
import { formatReceiptDate } from '../../src/utils/format';
import { EnterpriseApp } from './enterprise-app';
import { EnterpriseShell } from './enterprise-shell';

export function EnterpriseWaybill({ saleId }: { saleId: string }) { return <EnterpriseApp><EnterpriseWaybillView saleId={saleId} /></EnterpriseApp>; }

function EnterpriseWaybillView({ saleId }: { saleId: string }) {
  const { state, hasPermission } = useBusiness();
  const [generatedAt] = useState(() => new Date());
  const sale = state.sales.find((entry) => entry.id === saleId);
  const customer = state.customers.find((entry) => entry.id === sale?.customerId);
  if (!hasPermission('invoices.view')) return <EnterpriseShell active="Sales"><div className="page-content enterprise-document-missing"><ShieldAlert size={26} /><h1>Waybill access restricted</h1><p>This role is not authorized to view fulfilment documents.</p><Link className="secondary-button" href="/dashboard"><ArrowLeft size={14} /> Return to dashboard</Link></div></EnterpriseShell>;
  if (!sale || !customer) return <EnterpriseShell active="Sales"><div className="page-content enterprise-document-missing"><FileText size={26} /><h1>Waybill not found</h1><p>The invoice or customer record required for this waybill is unavailable.</p><Link className="secondary-button" href="/sales"><ArrowLeft size={14} /> Return to Sales</Link></div></EnterpriseShell>;
  const profile = state.businessProfile;
  const waybillNumber = `${profile.waybillPrefix || 'WAY-'}${sale.invoiceNumber.split('-').pop()}`;
  return <EnterpriseShell active="Sales"><div className="page-content waybill-native-page"><header className="document-page-toolbar no-print"><div><Link className="icon-button" title="Return to invoice" href={`/sales/${sale.id}`}><ArrowLeft size={16} /></Link><div><p className="eyebrow">Fulfilment document</p><h1>{waybillNumber}</h1><span>Invoice {sale.invoiceNumber} · {customer.name}</span></div></div>{hasPermission('invoices.print') ? <button className="primary-button" type="button" onClick={() => window.print()}><Printer size={14} /> Print waybill</button> : null}</header>
    <article className="enterprise-paper waybill-paper"><header className="paper-document-header waybill-paper-header"><div className="paper-business"><div className="paper-logo">{profile.logoUrl ? <Image src={profile.logoUrl} width={54} height={54} unoptimized alt={`${profile.businessName} logo`} /> : profile.businessName.slice(0, 2).toUpperCase()}</div><div><strong>{profile.businessName}</strong><span>Official delivery document</span></div></div><div className="paper-document-title"><h2>Waybill</h2><strong>{waybillNumber}</strong><span>Dispatch: {formatReceiptDate(sale.createdAt)}</span></div></header>
      <section className="waybill-party-grid"><div><p>Sender / Consignor</p><h3>{profile.businessName}</h3><span>{profile.address || 'Address not configured'}</span><span>{profile.phone || 'Phone not configured'}</span><span>{profile.website}</span></div><div><p>Recipient / Consignee</p><h3>{customer.name}</h3><span>Client ID: {customer.clientId}</span><span>{customer.phone || customer.whatsapp || 'Phone not recorded'}</span><span>{customer.email}</span></div></section>
      <table className="waybill-line-table"><thead><tr><th>No.</th><th>Goods description</th><th>Unit</th><th>Quantity</th></tr></thead><tbody>{sale.items.map((item, index) => { const product = state.products.find((entry) => entry.id === item.productId); return <tr key={`${sale.id}-${item.productId}`}><td>{index + 1}</td><td><strong>{item.productName}</strong><span>{item.inventoryId}</span></td><td>{product?.unit || 'Units'}</td><td>{item.quantity}</td></tr>;})}{Array.from({ length: Math.max(0, 5 - sale.items.length) }, (_, index) => <tr className="waybill-empty-row" key={`empty-${index}`}><td /><td /><td /><td /></tr>)}</tbody></table>
      <section className="waybill-reference-strip"><span><strong>Reference invoice</strong>{sale.invoiceNumber}</span><span><strong>Origin</strong>{profile.country?.trim() || 'GH'}</span><span><strong>System ID</strong>{sale.id.slice(0, 8)}</span></section>
      <section className="waybill-signatures"><div><span>Dispatched by</span><i /><strong>Warehouse stamp</strong></div><div><span>Messenger / carrier</span><i /><strong>Delivery officer</strong></div><div><span>Received in good condition</span><i /><strong>Consignee signature</strong></div></section>
      <footer className="paper-footer"><p>This waybill is the logistics record for goods in transit under invoice {sale.invoiceNumber}.</p><span>Generated by BizPilot Enterprise · {generatedAt.toLocaleDateString()} {generatedAt.toLocaleTimeString()} · Page 1 of 1</span></footer>
    </article>
  </div></EnterpriseShell>;
}
