-- Atomically records customer receipts for owner and employee sessions.
-- The payment id is the idempotency key: replaying the same command is safe.

create or replace function public.record_receivable_payment_command(
  credential_identifier text,
  credential_password text,
  workflow_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  employee_record public.employee_credentials%rowtype;
  invoice_record public.invoices%rowtype;
  requested_business_id uuid;
  requested_invoice_id uuid;
  requested_payment_id text := nullif(trim(coalesce(workflow_payload->>'paymentId', '')), '');
  requested_payment_code text := nullif(trim(coalesce(workflow_payload->>'paymentCode', '')), '');
  requested_ledger_entry_number text := nullif(trim(coalesce(workflow_payload->>'ledgerEntryNumber', '')), '');
  requested_activity_id text := nullif(trim(coalesce(workflow_payload->>'activityId', '')), '');
  requested_activity_number text := nullif(trim(coalesce(workflow_payload->>'activityNumber', '')), '');
  requested_notification_id text := nullif(trim(coalesce(workflow_payload->>'notificationId', '')), '');
  requested_amount numeric := coalesce(nullif(workflow_payload->>'amount', '')::numeric, 0);
  requested_method text := trim(coalesce(workflow_payload->>'method', ''));
  requested_reference text := nullif(trim(coalesce(workflow_payload->>'reference', '')), '');
  requested_created_at timestamptz := coalesce(nullif(workflow_payload->>'createdAt', '')::timestamptz, now());
  actor_id text;
  actor_role text;
  amount_due numeric;
  next_paid_amount numeric;
  remaining_balance numeric;
  invoice_payment_method text;
  ledger_payment_method text;
  settled boolean;
begin
  begin
    requested_business_id := nullif(workflow_payload->>'businessId', '')::uuid;
    requested_invoice_id := nullif(workflow_payload->>'saleId', '')::uuid;
  exception when invalid_text_representation then
    raise exception 'Business and invoice ids must be valid UUIDs';
  end;

  if requested_business_id is null or requested_invoice_id is null or requested_payment_id is null or requested_payment_code is null then
    raise exception 'Business, invoice, payment id, and payment code are required';
  end if;
  if requested_ledger_entry_number is null or requested_activity_id is null
    or requested_activity_number is null or requested_notification_id is null then
    raise exception 'Ledger, activity, and notification evidence is required';
  end if;
  if requested_amount <= 0 then raise exception 'Payment amount must be greater than zero'; end if;
  if requested_method not in ('cash', 'bank', 'mobileMoney', 'creditCard') then raise exception 'Unsupported payment method'; end if;

  if auth.uid() is not null and exists (
    select 1 from public.businesses
    where id = requested_business_id and owner_id = auth.uid()
  ) then
    actor_id := auth.uid()::text;
    actor_role := 'Owner';
  else
    select * into employee_record
    from public.employee_credentials
    where account_status = 'active'
      and business_id = requested_business_id
      and password_hash is not null
      and password_hash = extensions.crypt(trim(credential_password), password_hash)
      and (lower(email) = lower(trim(credential_identifier)) or lower(username) = lower(trim(credential_identifier)))
    limit 1;

    if employee_record.id is null then raise exception 'Invalid employee credentials'; end if;
    if 'payments.record' = any(coalesce(employee_record.revoked_permissions, '{}')) then
      raise exception 'Payment recording has been revoked for this employee';
    end if;
    if employee_record.role not in ('GeneralManager', 'Accountant', 'StoreManager')
      and not ('payments.record' = any(coalesce(employee_record.granted_permissions, '{}'))) then
      raise exception 'This employee is not authorized to record customer payments';
    end if;
    actor_id := employee_record.id::text;
    actor_role := employee_record.role;
  end if;

  -- Sequence-based business references are generated by clients. Serialize commands
  -- for a business so two devices cannot commit the same reference concurrently.
  perform pg_advisory_xact_lock(hashtextextended(requested_business_id::text, 0));

  select * into invoice_record
  from public.invoices
  where id = requested_invoice_id and business_id = requested_business_id
  for update;

  if invoice_record.id is null then raise exception 'Invoice not found for this business'; end if;

  if exists (
    select 1 from public.payments
    where id = requested_payment_id
      and business_id = requested_business_id
      and source_type = 'invoice'
      and source_id = requested_invoice_id::text
  ) then
    amount_due := coalesce(invoice_record.net_receivable_amount, invoice_record.total_amount);
    return jsonb_build_object(
      'ok', true,
      'idempotent', true,
      'paidAmount', invoice_record.paid_amount,
      'balance', greatest(0, amount_due - invoice_record.paid_amount)
    );
  end if;

  if lower(invoice_record.status) = 'reversed' then raise exception 'Payments cannot be recorded against a reversed invoice'; end if;
  amount_due := coalesce(invoice_record.net_receivable_amount, invoice_record.total_amount);
  remaining_balance := greatest(0, amount_due - invoice_record.paid_amount);
  if remaining_balance <= 0 then raise exception 'This invoice has already been settled'; end if;
  if requested_amount > remaining_balance then raise exception 'Payment cannot exceed the remaining invoice balance'; end if;

  next_paid_amount := round(invoice_record.paid_amount + requested_amount, 2);
  remaining_balance := round(greatest(0, amount_due - next_paid_amount), 2);
  settled := remaining_balance = 0;
  invoice_payment_method := case requested_method when 'mobileMoney' then 'mobile_money' when 'cash' then 'cash' else 'bank_account' end;
  ledger_payment_method := case requested_method when 'mobileMoney' then 'mobile_money' when 'cash' then 'cash' else null end;

  update public.invoices
  set paid_amount = next_paid_amount,
      payment_method = invoice_payment_method,
      payment_reference = coalesce(requested_reference, payment_reference),
      updated_at = requested_created_at
  where id = requested_invoice_id and business_id = requested_business_id;

  insert into public.payments (id, business_id, payment_code, source_type, source_id, amount, method, reference, recorded_by, created_at)
  values (requested_payment_id, requested_business_id, requested_payment_code, 'invoice', requested_invoice_id::text, requested_amount, requested_method, requested_reference, actor_id, requested_created_at);

  insert into public.customer_ledger_entries (business_id, entry_number, customer_id, entry_type, amount_delta, invoice_id, reference_number, payment_method, note, created_at)
  values (
    requested_business_id,
    requested_ledger_entry_number,
    invoice_record.customer_id,
    'payment_received',
    -requested_amount,
    requested_invoice_id,
    requested_payment_code,
    ledger_payment_method,
    'Payment received for ' || invoice_record.invoice_number,
    requested_created_at
  );

  insert into public.business_audit_events (id, business_id, activity_number, entity_type, entity_id, action_type, title, detail, status, reference_number, related_sale_id, actor_user_id, actor_role, created_at)
  values (
    requested_activity_id, requested_business_id, requested_activity_number,
    'sale', requested_invoice_id::text, 'payment_recorded',
    case when settled then 'Invoice settled' else 'Customer payment recorded' end,
    requested_payment_code || ' recorded ' || requested_amount || case when settled then '. No balance remains.' else '. Balance remaining: ' || remaining_balance || '.' end,
    'success', invoice_record.invoice_number, requested_invoice_id::text, actor_id, actor_role, requested_created_at
  );

  insert into public.app_notifications (id, business_id, title, message, recipient_roles, entity_type, entity_id, reference_number, action_url, created_at)
  values (
    requested_notification_id, requested_business_id,
    case when settled then 'Customer invoice settled' else 'Customer payment recorded' end,
    requested_payment_code || ' recorded ' || requested_amount || ' against ' || invoice_record.invoice_number || case when settled then '. The invoice is fully paid.' else '. ' || remaining_balance || ' remains outstanding.' end,
    array['SalesManager', 'GeneralManager', 'Accountant'], 'sale', requested_invoice_id::text,
    invoice_record.invoice_number, '/sales/' || requested_invoice_id::text, requested_created_at
  );

  return jsonb_build_object('ok', true, 'idempotent', false, 'paidAmount', next_paid_amount, 'balance', remaining_balance);
end;
$$;

revoke all on function public.record_receivable_payment_command(text, text, jsonb) from public;
grant execute on function public.record_receivable_payment_command(text, text, jsonb) to anon, authenticated;
